import Navbar from "@/components/common/Navbar";
import "../globals.css";
import Footer from "@/components/common/Footer";
import { Montserrat } from "next/font/google";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
  display: "swap",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-white">
      <body
        className={`antialiased ${montserrat.className} `}
        suppressHydrationWarning
      >
        <div className="w-full h-[140px] lg:h-[114px] bg-white flex items-center shadow-md">
          <Navbar />
        </div>
        {children}
        <Footer />
      </body>
    </html>
  );
}
